version: '3'

services:
  php:
    environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=${DATABASE_URL}
  server:
    ports:
      - '80:80'
      - '443:443'