version: '3'

services:
  php:
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: server
      dockerfile: Dockerfile
      target: php_dev
    volumes:
      - ./server/.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/server/.config/composer:/home/prod/.composer
      - ./server:/srv/app
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://app:password@database:5432/app?serverVersion=15&charset=utf8}
  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "app" ]
      interval: 5s
      timeout: 5s
      retries: 5
