export const IconName = [
  "check-circle",
  "cross",
  "cross-circle",
  "cross-square",
  "denied",
  "warningTag",
  "arrow",
  "gare",
  "gear",
  "loupe",
  "moon",
  "pin",
  "placeholder",
  "plus",
  "profile",
  "reversed-arrow",
  "screen",
  "getIn",
  "chevron",
  "move",
  "long-arrow",
  "trash",
  "download",
  "sun",
  "export",
  "warning",
  "logout",
  "pencil",
  "pencil-off",
  "loading",
  "outline-sync",
  "upload",
  "unknown",
  "tabler-sender",
  "database-checked",
  "database-remove",
];

export const Dimension = [4.8, 8, 12, 16, 20, 24, 28, 32, 48];

export const FontSize = ["12", "14", "16", "20", "24"];
