---
- hosts: all
  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/ThibautSembeni/challenge_s5.git
        dest: ~/app
        clone: yes
        update: yes
        force: yes
    - name: install pip docker
      import_tasks: docker/docker-pip.yml
      become: yes
    - name: Basic usage
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'APP_ENV') }}' is the APP_ENV environment variable."
    - name: Template a file
      ansible.builtin.template:
        src: ./env.j2
        dest: ~/app/.env
        mode: "0600"

- hosts: all
  name: Run using a project directory
  tasks:
    - name: Create and pull compose services
      community.docker.docker_compose:
        project_src: app
        files: docker-compose.prod.yml
        pull: true
        state: present
      register: output