name: CI - Back Tests
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  test:
    name: Run Functional tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
        APP_ENV: test
        APP_SECRET: 123456
        DATABASE_URL: postgresql://app:password@127.0.0.1:5432/app?serverVersion=15&charset=utf8
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: app
          POSTGRES_PASSWORD: password
          POSTGRES_USER: app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build php

      - name: Start services
        run: docker compose up -d php

      - name: Install dependencies
        run: docker compose exec -T php composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: docker-compose exec -T php ./vendor/bin/phpunit tests