name: CI - Back Tests
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  test:
    name: Run Functional tests
    runs-on: ubuntu-latest
    env:
        APP_ENV: test
        APP_SECRET: 123456
        DATABASE_URL: postgresql://app:password@database:5432/app?serverVersion=15&charset=utf8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          load: true
          files: |
            docker-compose.test.yml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        run: docker compose -f docker-compose.test.yml up -d

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(docker compose exec -T php composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: docker compose -f docker-compose.test.yml exec -T php composer install --prefer-dist --no-progress --no-suggest

      - name: Generate JWT keys
        run: docker-compose -f docker-compose.test.yml exec -T php bin/console lexik:jwt:generate-keypair --overwrite --no-interaction

      -
        name: Create test database
        run: docker compose -f docker-compose.test.yml exec -T php bin/console -e test doctrine:database:create
      -
        name: Run migrations
        run: docker compose -f docker-compose.test.yml exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit tests
        run: docker-compose -f docker-compose.test.yml exec -T php ./vendor/bin/phpunit tests