name: CI - New Front Tests
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  test:
    name: Run Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          targets: 'client'
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7