name: Mise en production

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflows }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Deploi API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
#        with:
#          ssh-private-key: ${{ secrets.OVH_SSH_KEY }}
#          ssh-host: ${{secrets.OVH_VM_IP}}
      - name: Set environment variables from secrets
        run: |
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> $GITHUB_ENV
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "SERVER_NAME=${{ secrets.SERVER_NAME }}" >> $GITHUB_ENV

      - name: Update docker compose image
        uses: dawidd6/action-ansible-playbook@v2
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CORS_ALLOW_ORIGIN: ${{ secrets.CORS_ALLOW_ORIGIN }}
          TWILIO_DSN: ${{ secrets.TWILIO_DSN }}
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PUBLIC_APP_URL: ${{ secrets.PUBLIC_APP_URL }}
        with:
          known_hosts: |
            ${{secrets.OVH_VM_IP}} ${{secrets.OVH_VM_KNOW_HOST}}
          inventory: |
            [all]
            ${{secrets.OVH_VM_IP}} ansible_user=debian
          # Required, playbook filepath
          playbook: ovh-vm-update.yml
          # Optional, directory where playbooks live
          directory: ./ansible
          # Optional, SSH private key
          key: ${{secrets.OVH_SSH_KEY}}